plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
}

// Android owns its service credentials code generation. Missing secrets keep
// the app buildable while disabling only the dependent features.
val generateAppSecrets = tasks.register("generateAppSecrets") {
    group = "codegen"
    description = "Generates Android service credentials from <root>/secrets.json."

    val secretsFile = rootProject.layout.projectDirectory.file("secrets.json").asFile
    val outputDir = layout.buildDirectory.dir("generated/appSecrets/kotlin")

    inputs.files(secretsFile).withPropertyName("secretsJson")
    outputs.dir(outputDir).withPropertyName("generatedSecretsDir")

    doLast {
        var readAccessToken = ""
        var apiKey = ""
        var wyzieApiKey = ""
        if (secretsFile.exists()) {
            val parsed = groovy.json.JsonSlurper().parse(secretsFile) as? Map<*, *>
            readAccessToken = (parsed?.get("TMDB_READ_ACCESS_TOKEN") as? String)?.trim().orEmpty()
            apiKey = (parsed?.get("TMDB_API_KEY") as? String)?.trim().orEmpty()
            wyzieApiKey = (parsed?.get("WYZIE_API_KEY") as? String)?.trim().orEmpty()
        }

        fun escape(value: String): String = value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("$", "\\$")
            .replace("\n", "\\n")

        val packageDir = outputDir.get().asFile.resolve("com/babasama/edendale")
        packageDir.mkdirs()
        packageDir.resolve("TmdbSecrets.kt").writeText(
            """
            |// Generated by :generateAppSecrets from <root>/secrets.json.
            |// Do not edit or commit; this file lives under build/.
            |package com.babasama.edendale
            |
            |internal object TmdbSecrets {
            |    val readAccessToken: String = "${escape(readAccessToken)}"
            |    val apiKey: String = "${escape(apiKey)}"
            |}
            |""".trimMargin()
        )
        packageDir.resolve("WyzieSecrets.kt").writeText(
            """
            |// Generated by :generateAppSecrets from <root>/secrets.json.
            |// Do not edit or commit; this file lives under build/.
            |package com.babasama.edendale
            |
            |internal object WyzieSecrets {
            |    val apiKey: String = "${escape(wyzieApiKey)}"
            |}
            |""".trimMargin()
        )
    }
}

kotlin {
    jvmToolchain(17)
    sourceSets.named("main") {
        kotlin.srcDir(generateAppSecrets)
    }
}

android {
    namespace = "com.babasama.edendale.android"
    compileSdk = libs.versions.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.babasama.edendale"
        minSdk = libs.versions.minSdk.get().toInt()
        targetSdk = libs.versions.targetSdk.get().toInt()
        versionCode = 1
        versionName = "0.26"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }
}

dependencies {
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)
    implementation(platform(libs.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.compose.material3)
    implementation(libs.compose.material.icons.extended)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.coil.compose)
    implementation(libs.androidx.documentfile)
    implementation(libs.media3.exoplayer)
    implementation(libs.media3.ui)
    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)
    implementation(libs.jcifs.ng)
    implementation(libs.androidx.security.crypto)
    implementation(libs.zxing.core)
    debugImplementation(libs.compose.ui.tooling)

    // JVM unit tests only (src/test): the suite is hermetic — no emulator or
    // network — and covers Android's domain, TMDB mapping, presentation, and
    // SMB URL logic rather than the Compose layer.
    testImplementation(libs.kotlin.test)
    testImplementation(libs.junit)
}
