#!/usr/bin/env python3
"""Compile Edendale.Windows/FrameGeneration/FrameGeneration.cu to PTX.

The app loads the PTX through the CUDA driver API (cuModuleLoadData), so the
driver compiles it for whichever NVIDIA GPU is installed and no CUDA runtime
ships with Edendale. Run this after changing the .cu file and commit the
regenerated FrameGeneration.ptx next to it.

Needs only NVRTC, for example from pip, with no CUDA toolkit install:

    pip install nvidia-cuda-nvrtc-cu12
    python3 tools/build-frame-generation-ptx.py [--nvrtc /path/to/libnvrtc.so.12]

The PTX targets compute_52 (GeForce 900 series and newer). Its .version line
is lowered to 7.0 so drivers from R450 on can load it; the kernels use no
newer PTX features. Pass --ptxas to also assemble the result as a check.
"""
import argparse
import ctypes
import glob
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'Edendale.Windows', 'FrameGeneration', 'FrameGeneration.cu')
OUTPUT = os.path.join(ROOT, 'Edendale.Windows', 'FrameGeneration', 'FrameGeneration.ptx')
ARCHITECTURE = 'compute_52'
PTX_VERSION = '7.0'


def find_nvrtc(explicit):
    if explicit:
        return explicit
    candidates = []
    try:
        import nvidia.cuda_nvrtc  # type: ignore
        base = list(nvidia.cuda_nvrtc.__path__)[0]
        candidates += glob.glob(os.path.join(base, 'lib', 'libnvrtc.so*'))
        candidates += glob.glob(os.path.join(base, 'bin', 'nvrtc64_*.dll'))
    except ImportError:
        pass
    candidates += glob.glob('/usr/local/cuda/lib64/libnvrtc.so*')
    if not candidates:
        sys.exit('NVRTC not found; pass --nvrtc or pip install nvidia-cuda-nvrtc-cu12')
    return sorted(candidates)[0]


def compile_ptx(nvrtc_path):
    nvrtc = ctypes.CDLL(nvrtc_path)
    source = open(SOURCE, 'rb').read()
    program = ctypes.c_void_p()

    def check(result, what):
        if result != 0:
            nvrtc.nvrtcGetErrorString.restype = ctypes.c_char_p
            sys.exit(f'{what} failed: {nvrtc.nvrtcGetErrorString(result).decode()}')

    check(nvrtc.nvrtcCreateProgram(ctypes.byref(program), source, b'FrameGeneration.cu', 0, None, None),
          'nvrtcCreateProgram')
    options = [f'--gpu-architecture={ARCHITECTURE}'.encode(), b'--use_fast_math', b'-default-device']
    array = (ctypes.c_char_p * len(options))(*options)
    result = nvrtc.nvrtcCompileProgram(program, len(options), array)

    size = ctypes.c_size_t()
    nvrtc.nvrtcGetProgramLogSize(program, ctypes.byref(size))
    log = ctypes.create_string_buffer(size.value)
    nvrtc.nvrtcGetProgramLog(program, log)
    if log.value.strip():
        print(log.value.decode(), file=sys.stderr)
    check(result, 'nvrtcCompileProgram')

    nvrtc.nvrtcGetPTXSize(program, ctypes.byref(size))
    ptx = ctypes.create_string_buffer(size.value)
    check(nvrtc.nvrtcGetPTX(program, ptx), 'nvrtcGetPTX')
    nvrtc.nvrtcDestroyProgram(ctypes.byref(program))
    return ptx.value.decode()


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--nvrtc', help='path to libnvrtc.so or nvrtc64_*.dll')
    parser.add_argument('--ptxas', help='path to ptxas, to assemble the PTX as a check')
    args = parser.parse_args()

    ptx = compile_ptx(find_nvrtc(args.nvrtc))
    ptx = re.sub(r'^\.version \d+\.\d+$', f'.version {PTX_VERSION}', ptx, count=1, flags=re.M)
    header = ('//\n// Generated by tools/build-frame-generation-ptx.py from FrameGeneration.cu.\n'
              '// Do not edit; change the .cu file and run the script again.\n//\n')
    with open(OUTPUT, 'w', newline='\n') as handle:
        handle.write(header + ptx.replace('\r\n', '\n'))
    print(f'wrote {os.path.relpath(OUTPUT, ROOT)} ({len(ptx)} bytes)')

    if args.ptxas:
        subprocess.run([args.ptxas, '--gpu-name', 'sm_52', '-O3', OUTPUT, '-o', os.devnull], check=True)
        subprocess.run([args.ptxas, '--gpu-name', 'sm_86', '-O3', OUTPUT, '-o', os.devnull], check=True)
        print('ptxas: assembles for sm_52 and sm_86')


if __name__ == '__main__':
    main()
